### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by pimterry** [konsumer/rawprotoparse#2]
This applies to rawproto too - in both cases, it'd be super useful to have types included, and I think they're really simple so it's very easy.

In my case, I've added a tiny declaration in my project to use rawprotoparse, which looks like:

```typescript
declare module 'rawprotoparse' {
    function parseRawProto(
        data: Uint8Array,
        prefix?: string,
        stringMode?: 'auto' | 'string' | 'buffer',
        arrayMode?: boolean
    ): any;

    export = parseRawProto;
}
```

The return type could be more explicit since the values are somewhat limited (and the valid field names are actually known, given the prefix argument) but I doubt it's worth it really, it's effectively unstructured data. Could also be `unknown` if you want to ensure that people check values, but I think that's more inconvenient than helpful.

**Comment by konsumer** [comment]
I am not a typescript user, so I am not sure what to do with this. Can I put it in a file alongside my js? I'd rather not switch my project to be a "typescript library" that requires a typescript build-chain, etc, but I am willing to add a single file somewhere, if typescript users will benefit from it, and it doesn't hurt the existing stuff.

**Comment by konsumer** [comment]
I don't personally find these sort of popups useful (and that is the main reason I don't use VSCode, because I find it extremely distracting) but adding some jsdoc may serve the same purpose. Does this work for you?

<img width="1173" alt="Screenshot 2024-03-07 at 11 12 06 AM" src="https://github.com/konsumer/rawprotoparse/assets/83857/6a73794e-1e24-4246-a372-17cac9972d76">

See [here](https://github.com/konsumer/rawprotoparse/blob/3d625d235a0f4faf42be1494420d38883224dec7/rawproto.js#L61-L71)

Additionally, I added a  .prettierrc file. I use [standardjs](https://standardjs.com/) so there is no configuration of code-style, but this will help inform other editors (VSCode, for example.) If this works for you, I can re-publish.

**Comment by pimterry** [comment]
For me at least, the goal isn't vs code doc popups - the types are used in the build process, so the project will fail to build if there's a possibility I'm passing invalid arguments or using a result unsafely. That will be generally true for most downstream typescript usage.

Fixing this generally requires a `.d.ts` file, either in the project or provided elsewhere. While jsdoc is used by VS code to provide documentation support, I don't think it's sufficient for TypeScript use in most cases.

Fortunately though it turns out it's easy to generate this from jsdoc automatically :smile:. I've just opened #3 to do that. I think with that in place, that'd resolve this issue.

**Comment by konsumer** [comment]
Sweet. merged.
